services:
  target1:
    image: ansible-target
    hostname: srv1
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    tmpfs:
      - /tmp
      - /run
    ports:
      - 192.168.24.1:22:22
      - 192.168.24.1:80:80
      - 192.168.24.1:443:443
  target2:
    image: ansible-target
    hostname: srv2
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    tmpfs:
      - /tmp
      - /run
    ports:
      - 192.168.24.2:22:22
      - 192.168.24.2:80:80
      - 192.168.24.2:443:443
